-- Insert 5 properties for sale
INSERT INTO public.properties (title, location, price, type, builder, status, category, amenities, images, brochures, bedrooms, bathrooms, area, description) VALUES
('Luxury Villa in Bandra', 'Bandra West, Mumbai', '₹3.5 Cr', 'villa', 'Premium Builders', 'active', 'property', ARRAY['Swimming Pool', 'Gym', 'Garden', 'Security'], ARRAY['/src/assets/property-1.jpg'], ARRAY['https://example.com/brochure1.pdf'], '4 BHK', '4 Bath', '2500 sq ft', 'Stunning luxury villa with modern amenities and prime location.'),
('Modern Apartment in Powai', 'Powai, Mumbai', '₹1.8 Cr', 'apartment', 'Urban Developers', 'active', 'property', ARRAY['Gym', 'Parking', 'Security', 'Garden'], ARRAY['/src/assets/property-2.jpg'], ARRAY['https://example.com/brochure2.pdf'], '3 BHK', '3 Bath', '1800 sq ft', 'Contemporary apartment with lake views and excellent connectivity.'),
('Commercial Space in BKC', 'Bandra Kurla Complex, Mumbai', '₹5.2 Cr', 'commercial', 'Corporate Builders', 'active', 'property', ARRAY['Parking', 'Security', 'AC', 'Elevator'], ARRAY['/src/assets/property-3.jpg'], ARRAY['https://example.com/brochure3.pdf'], 'Office Space', '4 Bath', '3000 sq ft', 'Premium commercial space in Mumbai financial district.'),
('Penthouse in Worli', 'Worli, Mumbai', '₹6.8 Cr', 'apartment', 'Skyline Builders', 'active', 'property', ARRAY['Swimming Pool', 'Gym', 'Terrace', 'Security'], ARRAY['/src/assets/property-1.jpg'], ARRAY['https://example.com/brochure4.pdf'], '5 BHK', '5 Bath', '3500 sq ft', 'Exclusive penthouse with panoramic city and sea views.'),
('Row House in Thane', 'Thane West, Mumbai', '₹2.1 Cr', 'villa', 'Family Homes', 'active', 'property', ARRAY['Garden', 'Parking', 'Security'], ARRAY['/src/assets/property-2.jpg'], ARRAY['https://example.com/brochure5.pdf'], '3 BHK', '3 Bath', '2200 sq ft', 'Spacious row house perfect for families with private garden.');

-- Insert 5 rental properties
INSERT INTO public.properties (title, location, price, type, builder, status, category, amenities, images, brochures, bedrooms, bathrooms, area, description) VALUES
('Furnished Flat in Andheri', 'Andheri East, Mumbai', '₹45,000/month', 'apartment', 'Rental Solutions', 'active', 'rental', ARRAY['Furnished', 'WiFi', 'AC', 'Parking'], ARRAY['/src/assets/property-1.jpg'], ARRAY[], '2 BHK', '2 Bath', '1000 sq ft', 'Fully furnished apartment ready to move in with modern amenities.'),
('Studio in Malad', 'Malad West, Mumbai', '₹25,000/month', 'apartment', 'Quick Rentals', 'active', 'rental', ARRAY['Furnished', 'Security', 'Gym'], ARRAY['/src/assets/property-2.jpg'], ARRAY[], '1 BHK', '1 Bath', '600 sq ft', 'Compact studio apartment perfect for working professionals.'),
('Duplex in Goregaon', 'Goregaon East, Mumbai', '₹65,000/month', 'apartment', 'Premium Rentals', 'active', 'rental', ARRAY['Terrace', 'Parking', 'Security', 'Garden'], ARRAY['/src/assets/property-3.jpg'], ARRAY[], '3 BHK', '3 Bath', '1600 sq ft', 'Spacious duplex with private terrace and garden access.'),
('Office Space in Lower Parel', 'Lower Parel, Mumbai', '₹80,000/month', 'commercial', 'Business Rentals', 'active', 'rental', ARRAY['Parking', 'Security', 'AC', 'Conference Room'], ARRAY['/src/assets/property-1.jpg'], ARRAY[], 'Office', '2 Bath', '1200 sq ft', 'Modern office space in prime business district.'),
('Villa in Juhu', 'Juhu, Mumbai', '₹1,20,000/month', 'villa', 'Luxury Rentals', 'active', 'rental', ARRAY['Swimming Pool', 'Garden', 'Security', 'Parking'], ARRAY['/src/assets/property-2.jpg'], ARRAY[], '4 BHK', '4 Bath', '2800 sq ft', 'Luxury villa near beach with premium amenities.');

-- Insert 5 hostel properties  
INSERT INTO public.properties (title, location, price, type, builder, status, category, amenities, images, brochures, bedrooms, bathrooms, area, description) VALUES
('Student Hostel Powai', 'Powai, Mumbai', '₹12,000/month', 'hostel', 'Student Living', 'active', 'hostel', ARRAY['WiFi', 'Mess', 'Security', 'Laundry'], ARRAY['/src/assets/property-1.jpg'], ARRAY[], 'Shared', 'Common', '100 sq ft', 'Comfortable hostel for students near IIT Bombay with all facilities.'),
('PG for Working Women', 'Bandra West, Mumbai', '₹18,000/month', 'pg', 'Safe Stay', 'active', 'hostel', ARRAY['WiFi', 'Mess', 'Security', 'AC'], ARRAY['/src/assets/property-2.jpg'], ARRAY[], 'Single/Double', 'Common', '120 sq ft', 'Secure PG accommodation for working women with home-like environment.'),
('Boys Hostel Andheri', 'Andheri East, Mumbai', '₹10,000/month', 'hostel', 'Youth Housing', 'active', 'hostel', ARRAY['WiFi', 'Mess', 'Common Room', 'Security'], ARRAY['/src/assets/property-3.jpg'], ARRAY[], 'Shared', 'Common', '80 sq ft', 'Affordable hostel for students and working professionals.'),
('Co-living Space Malad', 'Malad West, Mumbai', '₹22,000/month', 'coliving', 'Modern Living', 'active', 'hostel', ARRAY['WiFi', 'Kitchen', 'Gym', 'Community Area'], ARRAY['/src/assets/property-1.jpg'], ARRAY[], 'Private', 'Shared', '150 sq ft', 'Modern co-living space with community facilities and private rooms.'),
('Executive PG Goregaon', 'Goregaon West, Mumbai', '₹15,000/month', 'pg', 'Executive Stay', 'active', 'hostel', ARRAY['WiFi', 'Mess', 'AC', 'Parking'], ARRAY['/src/assets/property-2.jpg'], ARRAY[], 'Single', 'Attached', '110 sq ft', 'Premium PG for working executives with attached bathrooms and parking.');