// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zovpozjgkwtsowjxxsvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdnBvempna3d0c293anh4c3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjUyMjUsImV4cCI6MjA2OTMwMTIyNX0.PnN2w3gUMUa68nkDdXJER5S2uLEbAtpUExP6KUIe5G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});